// This is the script file for this project written in JS technology...
// These are HTML elements captured in some constants for further DOM manipulation...
const toggle = document.getElementById("toggle");
const nav = document.getElementById("nav");

// This is for toggling between nav menu closing and opening...
toggle.addEventListener("click", () => nav.classList.toggle("active"));
